### ISSUE TITLE
Filters don't work across all paged results

### ISSUE THREAD

**Issue by sokratesagogo** [robincornett/sixtenpress-isotope#1]
Hi, nice plugin, but the filters don't seem to work across all paged results, only on the current page of results.

**Comment by robincornett** [comment]
Yes, at this point, the filters only work on the current page, and don't carry over to a page reload. I've tinkered a bit with maybe allowing infinite scroll, but it's taking some work, so at this point, allowing more posts on an isotope enabled archive is the more workable option.

**Comment by sokratesagogo** [comment]
Thanks for the reply Robin, your work is appreciated!
